config/routes.rb
Rails.application.routes.draw do
  resources :alarms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alarm.rb
class Alarm < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]

  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(alarm_params)
    require "net/http"
    require "uri"

    respond_to do |format|
      if @alarm.save
        format.html { redirect_to @alarm, notice: 'Alarm was successfully created.' }
        format.json { render :show, status: :created, location: @alarm }
        require "net/http"
        require "uri"
        uri = URI('http://www.handshake-bellbird.com/push')
        http = Net::HTTP.new(uri.host, uri.port)
        request = Net::HTTP::Post.new(uri.request_uri)
        request.set_form_data({"alarm_id" => @alarm.name, "per_page" => "50"})
        #response = http.request(request)
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.html { redirect_to @alarm, notice: 'Alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    #@alarm.destroy
    respond_to do |format|
      format.html { redirect_to alarms_url, notice: 'Alarm was successfully Upvoted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_params
      params.require(:alarm).permit(:name, :reason, :votes)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alarms/_form.html.erb
<%= form_with(model: alarm, local: true) do |form| %>
  <% if alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :alarm_name %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_field :reason, id: :alarm_reason %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alarms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Reason</th>
      <th>Votes</th>

      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @alarms.reverse.each do |alarm| %>
      <tr>
        <td><%= alarm.name.upcase %></td>
        <td><%= alarm.reason %></td>
        <td><%= 0  %></td>
        <td><%= link_to 'Show', alarm %></td>
        <td><%= link_to 'Upvote', alarm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alarm', new_alarm_path %>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Back', alarms_path %>

app/views/alarms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @alarm.name %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @alarm.reason %>
</p>

<%= link_to 'Back', alarms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alarms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>